### ISSUE TITLE
The Game Crashes whenever the trading depot activates with an andesite funnel attached to it

### ISSUE THREAD

**Issue by DubbEck** [cakeGit/Create-Trading-Floor#3]
[crash report.txt](https://github.com/user-attachments/files/17269407/crash.report.txt)
 So when testing the mod (for the 3rd time, before I didn't find anything to complain about) I ran into an unexpected crash i reproduced it by running the game without the mod so that the trading depots disapeer (it caused crashes whenever loading terrain basically), then trying a different configuration whenever I reopened the game with the mod installed. What I landed on is that brass funnels as the output work fine but when a villager interacts with a trading depot with an andesite funnel attached as output, the game crashes. I also recorded an overlook of this issue with obs, if that could help I can post it too. Thanks in advance, I adore this mod, best of luck troubleshooting

**Comment by DubbEck** [comment]
oh and the trade i was using is the [32 sticks -> 1 emerald] fletcher trade

**Comment by cakeGit** [comment]
I believe that this was fixed in 1.0.6, seems like the same error as the issue before, update and if that doesent work open a new issue, thanks for your time anyways ^^
