### ISSUE TITLE
Farmer not work. Crash danger with Numismatic

### ISSUE THREAD

**Issue by GaLUXy01** [cakeGit/Create-Trading-Floor#4]
Version: 1.19.2 Forge 43.4.0

Not working with Farmers.

Tested with an Armorer (Vanilla) and with a Wizard (from "My Village Pack" by libliga_) and both works.

Also tested with "Numismatic Overhaul: Reforged" by Nyfaria, which only changed Armorer's trades.
Giving silver coins for leggings works great, but it crashed by giving 4 iron ingots for 2 silver coins.

The crash occurs when the extractor funnel it's made of andesite, and keep crashing at world loading forever. 

[crash-2024-11-02_15.32.34-server.txt](https://github.com/user-attachments/files/17607359/crash-2024-11-02_15.32.34-server.txt)

Instead this configuration with brass funnel works.

![2024-11-02_15 49 13](https://github.com/user-attachments/assets/59b3a668-8a28-418b-8620-a0af031a6384)

![2024-11-02_15 49 44](https://github.com/user-attachments/assets/6df97bfd-c65d-45c4-a63c-69680ce69933)

![2024-11-02_15 50 25](https://github.com/user-attachments/assets/161bc804-7150-4521-a748-512726ec2b89)

![2024-11-02_15 55 50](https://github.com/user-attachments/assets/7def1684-91d1-4f10-b303-93ba1babea60)

**Comment by cakeGit** [comment]
Hi, thanks for the report, I'm working on a fix now

**Comment by cakeGit** [comment]
Forgot to mention - Fixed in latest version,

**Comment by GaLUXy01** [comment]
it works perfectly, both farmer and andesite funnel. Thank you so much
